---

- name: KAFKA | Installing dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ required_libs }}"
  tags:
    skip_ansible_lint

- name: KAFKA | Ensure kafka group
  group:
    name: "{{ kafka_group }}"

- name: KAFKA | Ensure kafka user
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    home: /bin/false

- name: KAFKA | Create install path
  file:
    path: "{{ kafka_install_path }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: KAFKA | Check kafka version
  command: bash -c "ls {{ kafka_install_path }}/libs | grep 'kafka_{{ scala_version }}-{{ kafka_version }}.jar'"
  register: kafka_check
  changed_when: false
  ignore_errors: true

- name: KAFKA | Untar kafka
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "{{ kafka_sources_url }}"
    remote_src: yes
    dest: "{{ kafka_install_path }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  when: 'kafka_force_reinstall or kafka_check|failed or kafka_check.stdout == ""'

- name: KAFKA | Copy Daemon script
  template:
    src: "{{ kafka_service_template_path }}"
    dest: /lib/systemd/system/kafka.service
    mode: 0644
  notify: restart kafka

- name: KAFKA | Create data path
  file:
    path: '{{ kafka_data_path }}'
    mode: 0760
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"