---

- name: KAFKA | Install
  include_tasks: install.yml
  tags:
    - kafka_install

- name: KAFKA | Configure
  include_tasks: config.yml
  tags:
    - kafka_configure

- name: KAFKA | Service
  include_tasks: service.yml
  tags:
    - kafka_service

- name: KAFKA | Topics
  include_tasks: topics.yml
  run_once: true
  tags:
    - kafka_topics
