---
kafka_zookeeper_hosts:
  - zookeeper:2181

kafka_version: 2.0.0

kafka_port: 9999

kafka_hosts:
  - host: kafka1
    id: 1
  - host: kafka2
    id: 2
  - host: kafka3
    id: 3

kafka_xmx: "768m"
kafka_xms: "512m"

kafka_topics:
  - name: 'test'
    partitions: '3'
    replicas: '3'
  - name: 'test2'
    partitions: '5'
    replicas: '1'

kafka_extra_properties:
  - key: message.max.bytes
    value: 409715200